### ISSUE TITLE
Facebook crawling with elastic

### ISSUE THREAD

**Issue by Songi221** [Norconex/committer-elasticsearch#10]
I think the ElasticsearchCommitter fits me well, but I got an error after the setup, and running.
```
INFO  [AbstractFileQueueCommitter] Committing 55 files
INFO  [ElasticsearchCommitter] Sending 55 operations to Elasticsearch.
INFO  [Node] [Wyatt Wingfoot] version[2.3.5], pid[49444], build[90f439f/2016-07-27T10:36:52Z]
INFO  [Node] [Wyatt Wingfoot] initializing ...
INFO  [PluginsService] [Wyatt Wingfoot] modules [], plugins [], sites []
INFO  [AbstractCrawler] Facebook Posts: Crawler executed in 1 second.
FATAL [JobSuite] Fatal error occured in job: Facebook Posts
INFO  [JobSuite] Running Facebook Posts: END (Thu Apr 06 15:14:07 CEST 2017)
FATAL [JobSuite] Job suite execution failed: Facebook Posts
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
	at org.elasticsearch.threadpool.ThreadPool.<clinit>(ThreadPool.java:190)
	at org.elasticsearch.node.Node.<init>(Node.java:170)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:150)
```

I arleady istalled elasticsearch and I'm able to put data in it so it works, I installed the committer 3.0 bc I found ur comment somewhere about that is the right version for elastic 5.x.
I put the jars to the lib folder as it is explaining. and set up the xml in this way:

```xml
<committer class="com.norconex.committer.elasticsearch.ElasticsearchCommitter">
  <indexname>events</indexname>
  <typename>face-crawled</typename>
  <clustername>data-mining</clustername>
  <clusterhosts>localhost</clusterhosts>
</committer>
```
which is matching the settings of my elasticsearch cluster, node and index.

I think somehow it doesn't find the right function.
can you help me out?
Thanks

**Comment by essiembre** [comment]
Which version of Elasticsearch?  I just tried the latest snapshot with elasticsearch 5.1 and 5.3 and I could not reproduce the problem.  Did you manually installed the Jars?  You may have duplicate jars (same jar with different versions). I recommend you try with the install script found when you expand the zip.

**Comment by Songi221** [comment]
I tried to run the install.sh and gave the lib to the script as it asks for it, and it don't install the files in it, just create an other lib folder, which I don't know how is it possible to have 2 folder with the same name in the same place but it manages to do it, it's on OSX. So thats why I copied them by hand. I use 5.3

**Comment by Songi221** [comment]
Thanks, the install script helped me, it works now.
