### ISSUE TITLE
settings.SettingsBuilder deprecated in 5.3.1

### ISSUE THREAD

**Issue by danizen** [Norconex/committer-elasticsearch#12]
https://github.com/elastic/elasticsearch/commit/42526ac28e07da0055faafca1de6f8c5ec96cd85

suggest a switch to bulder, or try/catch construct which tries SettingsBuilder and then builder.

**Comment by essiembre** [comment]
This is not an issue with the 3.0.0-SNAPSHOT version.   A new release was just made to ship with 5.3.1.  Please confirm.

**Comment by essiembre** [comment]
The new snapshot was actually made a few minutes after the previous post... in case you were too fast. :-)

**Comment by essiembre** [comment]
The Elasticsearch Committer v3.0.0 has been released, with support for Elasticsearch 5.x.
