### ISSUE TITLE
Upgrade Elasticsearch library to version 2.x (latest)

### ISSUE THREAD

**Issue by essiembre** [Norconex/committer-elasticsearch#2]
From @bruce-genhot at https://github.com/Norconex/collector-http/issues/190#issuecomment-161634436: 

> The elasticsearch committer library only works with elasticsearch 1.5, the latest version is 2.1.0. Hope the committer library can be upgrate as well.

**Comment by essiembre** [comment]
@bruce-genhot: Thanks to @pascaldimassimo,  the latest [snapshot release](http://www.norconex.com/collectors/committer-elasticsearch/download) now supports Elasticsearch 2.1.0.  Have a try and let us know if that works fine.

**Comment by bruce-genhot** [comment]
thanks to both of you! @essiembre , @pascaldimassimo
