### ISSUE TITLE
Field types as integer instead of text

### ISSUE THREAD

**Issue by jmrichardson** [Norconex/committer-elasticsearch#20]
I would like to be able to use the collector.lastmodified and collector.filesize as sort fields.  However, since they are mapped as "text" values, the sort does not work correctly on "text" values.  I tried mapping the field values as integer but got this error on commit:

```
{
    "_index": "wmsearch",
    "_type": "doc",
    "_id": "file:///c:/xxx",
    "status": 400,
    "error": {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [collector.lastmodified]",
        "caused_by": {
            "type": "number_format_exception",
            "reason": "For input string: \"1495129910000\""
        }
    }
}
```

Is it possible to change these field values from text to integer?  

I can think of a possible work-around such as creating a new field (called something else) with "integer" type, and use scripttagger or similar to copy the value to the new field so it can be used as a sort field in ES.  However, I am hoping this could be updated in a snapshot version.  Should I perform the workaround or do you think this could be changed in the ES committer?

Thanks

**Comment by essiembre** [comment]
"1495129910000" is already a numeric value.  Can it be that you are trying to fit a number too large for an "integer" type?  EPOCH dates are "long" (64 bytes).   Try changing your data type to long if it is not already and try it again.

**Comment by jmrichardson** [comment]
Thank you.  Changing to "long" did resolve the issue :)
