### ISSUE TITLE
Must I create index in Elasticsearch when using committer?

### ISSUE THREAD

**Issue by flochman** [Norconex/committer-elasticsearch#23]
Hi,

Hi I would like to use HTTP Collector with Elsticsearch Committer but do not know how to setup elasticsearch that will receive data from Elastic Committer.

here is my config in HTTP Collector:
```

<httpcollector id="Minimum Config HTTP Collector">

  <!-- Decide where to store generated files. -->
  <progressDir>./examples-output/minimum/progress</progressDir>
  <logsDir>./examples-output/minimum/logs</logsDir>

  <crawlers>
    <crawler id="Norconex Minimum Test Page">

      <!-- Requires at least one start URL (or urlsFile). 
           Optionally limit crawling to same protocol/domain/port as 
           start URLs. -->
      <startURLs stayOnDomain="true" stayOnPort="true" stayOnProtocol="true">
         <url>http://www.example.com</url>
		
      </startURLs>
      <robotsTxt ignore="true" />
      <!-- === Recommendations: ============================================ -->

      <!-- Specify a crawler default directory where to generate files. -->
      <workDir>./examples-output/minimum</workDir>

      <!-- Put a maximum depth to avoid infinite crawling (e.g. calendars). -->
      <maxDepth>20</maxDepth>

      <!-- We know we don't want to crawl the entire site, so ignore sitemap. -->
      <sitemapResolverFactory ignore="true" />

      <!-- Be as nice as you can to sites you crawl. -->
      <delay default="1" />
      
      
      <!-- Decide what to do with your files by specifying a Committer. -->

<committer class="com.norconex.committer.elasticsearch.ElasticsearchCommitter">
    <nodes>http://192.168.0.61:9200/</nodes>	
    <indexName>moj</indexName>
	<typeName>mojtype</typeName>
    <ignoreResponseErrors>false</ignoreResponseErrors>
	 
</committer>

    </crawler>
  </crawlers>

</httpcollector>

```

Have I create elasticsearch index with name "moj" ?

How I create typeName "mojtype" ?

Are index and type created automatically when committed to elasticsearch?

It is not clear what fields pump Elasticsearch Committer to Elasticsearch or what is index mapping for Elasticsearch.

Thanks.

**Comment by flochman** [comment]
OK. I found the problem.

In my XML config in committer section were missing

 ```
<queueSize>10</queueSize>
 <commitBatchSize>10</commitBatchSize>
```

fields.

By adding this fields to xml config committer and Collector automatic create index and type in Elasticsearch.

Thanks.

**Comment by essiembre** [comment]
These settings should not make a difference in the creation of the index.  There are default values being used for the queue size and commit batch size when you do not specify them.  Putting small numbers can influence how "soon" you are seeing something appear in Elasticsearch.

I am glad you have it working.  Chances are you will have way too many fields.  You may want only keep those that are of interest to you.  Also, Elasticsearch can try to dynamically create the proper field types for you, but it is sometimes best if you can define them yourself beforehand to make sure they are really the types you want.
