### ISSUE TITLE
fields into Elasticsearch

### ISSUE THREAD

**Issue by jacksonp2008** [Norconex/committer-elasticsearch#24]
Testing your products, so far crawler works and was much easier to follow than Nutch or Stormcrawler.

I am sending to elastic 5.6 and the data is there.  However, I am a bit confused on the fields as I am not seeing what I had expected.  I would like to see ALL available data fields sent to ES, and then I can pair back as needed.

In your example:
```
    <importer>
        <postParseHandlers>
          <!-- If your target repository does not support arbitrary fields,
               make sure you only keep the fields you need. -->
          <tagger class="com.norconex.importer.handler.tagger.impl.KeepOnlyTagger">
           <fields>title,keywords,description,document.reference</fields>
          </tagger>
        </postParseHandlers>
      </importer>
```
If I don't set <fields> it provides even less data in ES.  How can I send all data fields the crawler finds? (or... how do I know what data fields are available to set this value?)

Also confused on sourceContentField & targetContentField.  ie. what are the sourceContent fields to choose from?  I really want to end up with a field in ES that has all the text from the page or document.

Thanks!

**Comment by essiembre** [comment]
**About the importer:**
You can comment the whole ``KeepOnlyTagger`` block to get all fields it finds.  Another approach to help find what fields are discovered before documents are committed is to use the [DebugTagger](https://www.norconex.com/collectors/importer/latest/apidocs/com/norconex/importer/handler/tagger/impl/DebugTagger.html).  

**About the Elasticsearch Committer:**
The ``sourceContentField`` is for you to overwrite which field from the document being committed holds the document "content".  By default, it does not take a field, but rather the actual document content and for typical crawls, this is usually what you want and you can ignore this field.

The ``targetContentField`` is related.  That is in what Elasticsearch field the document content will be stored.  Default it is "content".

Does that answer?

**Comment by jacksonp2008** [comment]
Pascal, thank-you for taking the time to respond.  This is indeed very helpful and I am seeing all the data fields in kibana.  Two questions if I may.

Q1 -- I have set the committer as follows:

```
<committer class="com.norconex.committer.elasticsearch.ElasticsearchCommitter">
    <nodes>http://10.80.99.54:9200</nodes>
    <indexName>web</indexName>
    <typeName>spiderdata</typeName>
    <targetContentField>aaawebcontent</targetContentField>
</committer>
```
and yet my "aaawebcontent" field turns up empty.  I have included a screenshot "q1" which shows the data in kibana.

![q1](https://user-images.githubusercontent.com/1813327/32527415-c1d0e9d0-c3e2-11e7-8219-46a16e96bc53.png)

Q2 -- I enabled the debug tagger as you indicated with:

```
 <tagger class="com.norconex.importer.handler.tagger.impl.DebugTagger">
</tagger>
```
Doc says at default,  it should be sending all fields with debug level.  However, I don't find debug logs anywhere.  Can you please point me to the right location for these logs?

Many thanks!

**Comment by jacksonp2008** [comment]
Yes, in fact I am so pleased now that I understand how it works that I am going to use this for all my systems if I can work out the SSO.  Thank-you Pascal for taking the time to respond!

**Comment by essiembre** [comment]
No problem!  I am glad you like it.  Hopefully, SSO will not be a big deal to add.
