### ISSUE TITLE
<typeName> should be set to not requried

### ISSUE THREAD

**Issue by EH-Khiari** [Norconex/committer-elasticsearch#36]
To comply with ES 7.x, <typeName> should be set as an optional parameter since it's been removed from ES 7.x's mappings syntax.

**Comment by essiembre** [comment]
A new snapshot release was made to address this.  "typeName" is now optional.  Please confirm.

**Comment by EH-Khiari** [comment]
I ran a few crawls, I confirm that <typeName> no longer needs to be defined.
