### ISSUE TITLE
Remove warning “Specifying types in bulk requests is deprecated.”

### ISSUE THREAD

**Issue by EH-Khiari** [Norconex/committer-elasticsearch#37]
The warning “Specifying types in bulk requests is deprecated.” keeps on getting displayed when indexing documents to ES 7.x indices.

**Comment by essiembre** [comment]
A new snapshot release was made to address this.  "typeName" is now optional.  Please confirm.

**Comment by EH-Khiari** [comment]
I ran a few crawls, I confirm the warning no longer shows up.
