### ISSUE TITLE
Deletion not working when a non "document.reference" value is used

### ISSUE THREAD

**Issue by jetnet** [Norconex/committer-elasticsearch#38]
hello Pascal,

looks like an issue with deletion: docs don't get deleted from ES when the `sourceReferenceField ` parameter is used:
```
<sourceReferenceField keep="false">id</sourceReferenceField>
```
BTW, when "id" is equal to "document.reference", then deletion works fine.

Version: 
```
INFO  [AbstractCollector] Version: Norconex Committer Elasticsearch 4.1.0 (Norconex Inc.)
```

Thanks!

**Comment by jetnet** [comment]
I guess, it's a duplicate for https://github.com/Norconex/collector-http/issues/548

**Comment by essiembre** [comment]
Yes, it is a duplicate.  For now, see if you can rely on the ``document.reference``, with the help of the GenericURLNormalizer.
