### ISSUE TITLE
commiter-elasticsearch compatibility with elasticsearch v5.x

### ISSUE THREAD

**Issue by hamish-realise** [Norconex/committer-elasticsearch#8]
Have been testing out the http-connector using the commiter-elasticsearch but getting compatibility issues with v5.x of elasticsearch using either the node or transport client options.

from elasticsearch.log
[2016-12-22T10:05:35,975][WARN ][o.e.t.n.Netty4Transport  ] [wJOGjRs] exception caught on transport layer [[id: 0x8b922be6, L:/0:0:0:0:0:0:0:1:9300 - R:/0:0:0:0:0:0:0:1:53549]], closing connection
java.lang.IllegalStateException: Received message from unsupported version: [2.0.0] minimal compatible version is: [5.0.0]

Are there any planned updates to commiter-elasticsearch for v5.x compatibility or any known workarounds to get around this issue?

**Comment by essiembre** [comment]
The latest [3.0.0 snapshot release](http://www.norconex.com/collectors/committer-elasticsearch/download) now supports 5.x (tested with 5.1.2).  Only Transport Client is now supported.  Please test and confirm.

**Comment by danizen** [comment]
#12 is possibly related, I should try the snapshot first.

**Comment by essiembre** [comment]
The Elasticsearch Committer v3.0.0 has been released, with support for Elasticsearch 5.x.
